import React, { useContext } from "react";
import { Link, useNavigate } from "react-router-dom";
import { ArrowRight, Minus, Plus, ShoppingBag, Trash2 } from "lucide-react";
import { ShopContext } from "../Context/ShopContext";

export default function CartItems() {
  const { cartRows, addToCart, removeFromCart, getTotalCartAmount } = useContext(ShopContext);
  const navigate = useNavigate();
  return <main className="min-h-[70vh] py-8 sm:py-12"><div className="section-wrap"><p className="eyebrow mb-2">Your inventory / checkout prep</p><h1 className="mb-8 text-4xl font-bold sm:text-5xl">The <span className="text-[#c9ff3d]">bag.</span></h1>
    {!cartRows.length ? <div className="manga-grid rounded-lg border border-white/10 bg-[#17191e] px-5 py-16 text-center"><ShoppingBag className="mx-auto mb-4 text-[#9e7bff]" size={34} /><p className="eyebrow">No items collected yet</p><h2 className="text-2xl">Your bag is a blank page.</h2><p className="text-sm text-white/45">Find something that belongs in your next chapter.</p><Link to="/shop" className="acid-button mt-4">Browse the archive <ArrowRight size={16} /></Link></div> : <div className="grid items-start gap-6 lg:grid-cols-[1fr_340px]"> <div className="space-y-3">{cartRows.map(({ cartKey, product, size, quantity }) => <article key={cartKey} className="flex gap-3 rounded-lg border border-white/10 bg-[#17191e] p-3 sm:gap-5 sm:p-4"><Link to={`/product/${product.id}`} className="shrink-0"><img src={product.image} alt={product.name} className="h-28 w-24 rounded object-cover sm:h-36 sm:w-32" /></Link><div className="flex min-w-0 flex-1 flex-col"><p className="mono mb-1 text-[10px] uppercase tracking-wider text-[#9e7bff]">{product.category} · Size {size}</p><Link to={`/product/${product.id}`} className="line-clamp-2 text-sm font-bold sm:text-base">{product.name}</Link><p className="mono mt-2 text-sm font-bold text-[#c9ff3d]">₹{product.new_price}</p><div className="mt-auto flex items-center justify-between pt-3"><div className="flex items-center rounded border border-white/10"><button onClick={() => removeFromCart(cartKey)} className="grid h-8 w-8 place-items-center" aria-label="Decrease quantity"><Minus size={13} /></button><span className="mono w-8 text-center text-xs">{quantity}</span><button onClick={() => addToCart(product.id, size)} className="grid h-8 w-8 place-items-center" aria-label="Increase quantity"><Plus size={13} /></button></div><button onClick={() => { for (let i = 0; i < quantity; i += 1) removeFromCart(cartKey); }} className="grid h-9 w-9 place-items-center rounded text-white/40 hover:bg-red-400/10 hover:text-red-300" aria-label="Remove item"><Trash2 size={16} /></button></div></div></article>)}</div>
      <aside className="rounded-lg border border-white/10 bg-[#17191e] p-5 sm:p-6 lg:sticky lg:top-28"><p className="eyebrow">Mission summary</p><h2 className="mb-5 text-xl font-bold">Order total</h2><div className="space-y-3 border-b border-white/10 pb-4 text-sm"><div className="flex justify-between text-white/55"><span>Subtotal</span><span className="mono text-white">₹{getTotalCartAmount()}</span></div><div className="flex justify-between text-white/55"><span>Delivery</span><span className="text-[#c9ff3d]">Free</span></div></div><div className="flex justify-between py-4 text-lg font-bold"><span>Total</span><span className="mono text-[#c9ff3d]">₹{getTotalCartAmount()}</span></div><p className="mb-4 rounded border border-[#9e7bff]/25 bg-[#9e7bff]/10 p-3 text-xs leading-5 text-white/60">Demo checkout: placing your order will not charge you.</p><button onClick={() => navigate("/checkout")} className="acid-button w-full">Continue <ArrowRight size={16} /></button><Link to="/shop" className="mt-4 block text-center text-xs text-white/45 hover:text-[#c9ff3d]">Continue browsing</Link></aside>
    </div>}</div></main>;
}
